### ISSUE TITLE
Play more with BullMQ

### ISSUE THREAD

**Issue by zahid-self** [zahid-self/R-D-Things#1]
**Task Description**

- [ ] Play more with BullMQ Queue and Worker
- [ ] Run Queue and Worker from different node js process
- [ ] Scraper some data using Puppeteer and use BullMQ for make automation more robust
- [ ]
